language: node_js
sudo: false

# Keep this in sync with appveyor.yml
node_js:
- '6'
- '8'
- '10'

before_script:
# If this command fails and you can't fix it, file an issue and add an exception to .nsprc
- npm run nsp-check

# Keep this in sync with appveyor.yml
script:
## run eslint, flow and the unit test suite.
- COVERAGE=y NODE_ENV=production npm test

## NOTE: by setting the configured python to /bin/false we are forcing the production mode tests
## to fail if any of the dependencies is a binary dependency that is build using node-gyp.
- npm config set python /bin/false

## run functional test suite in a npm production environment
## (See #1082 for rationale).
- npm run copy-dist-files-to-artifacts-dir
- cd artifacts/production
- npm install --production; export NPM_INSTALL_EXIT_CODE=$?
- cd -
- test $NPM_INSTALL_EXIT_CODE -eq 0 &&
  TEST_WEB_EXT_BIN=./artifacts/production/bin/web-ext npm run test:functional

## NOTE: remove the custom python path from the npm config, and also
## remove production package.json (which seems to convince npm run travlis-pr-title-lint
## to look for grunt in the production node_modules/ dir).
- npm config delete python
- rm artifacts/production/package.json

## lint the github PR title.
- npm run travis-pr-title-lint

after_script: npm run publish-coverage

before_deploy:
## Make sure we have a production build.
- NODE_ENV=production npm run build

notifications:
  irc:
    channels:
    - irc.mozilla.org#amo-bots
    on_success: change
    on_failure: always
deploy:
  provider: npm
  email: addons-dev-automation+npm@mozilla.com
  # Note that cleanup runs *after* the before_deploy script.
  skip_cleanup: true
  # This is the API key for npm user 'addons-robot'
  api_key:
    secure: gMZR5u6VxrXFxTigPlaoCre+SpFWf2dp3nsjYqYfvSW7eVqy9WtZpxOxJaNMn4Fwo+U8BVz7u23sugC/gm6JwjhIjVb20dwHhKJd1rjo4U+1Dbf9IdGysNWE6FYi3IKr2HpB/lht2HFb3+X01bLgB0xcTY459HOorAIDinTvrMMlmilV0S+sp9MeYjbcNl+tT71raVf4O2AJqsI1cA5yDLc3lhoNd87l7aB/+3AR3Vvbt0HymuzZJBz5dY5txxw2m53jPIj4Dxj6RMwsJ7fuEESkM0Da26ViOEuK+4zvwt/HhUFeDveKyOZklX7tLHg9m5MhOrnRsRRvGTxi+jIGlyO9NHhKMaK7Cvlp3K9DzTSpyilNFjEzmAE6H6HiI/DfdrmvD365RJU1SE/3R77c/n3GROmka/m9g6dJXteScoA2kitFizjnkMwPdPunZP2OXl8kUGeA3VIIDF03JXTFPz+bjNslmO0u5Y4vuKBy3fVhoxMd0c8hb+okCbkFJSwHVM4qWmLPYarN8I1XxmcVuJWbrjnFo8EAgaFXwge4PoglZsmCo0oDbM7IC0DirCsCiq4Fj+U2mrIA7k/9EVQ/i/3t2NCZ5xDdTyQzhqRx78lJt2Wr2lhx7kImiZ8SiFrIsAjkLvU4P8zE66eOpfgMAHdDDQAX9PA08Twyp1IG8Bk=
  on:
    tags: true
