language: node_js
sudo: false

os:
- linux
- windows

node_js:
- '10'
- '12'

# Skip node_js 6 on travis windows workers (as it often fails because
# travis fails to init the node_js 6 environment).
matrix:
  fast_finish: true
  exclude:
  - node_js: '10'
    os: windows

jobs:
  include:
  - stage: npm audit and lint github PR title
    ## Keep this in sync with the last version listed in the node_js property.
    node_js: '12'
    os: linux
    script:
    - npm run audit-deps
    - npm run travis-pr-title-lint
  - stage: deploy on npm
    ## Keep this in sync with the last version listed in the node_js property.
    node_js: '12'
    os: linux
    script: echo "Deploying to npm..."
    ## Make sure we have a production build.
    before_deploy: NODE_ENV=production npm run build
    deploy:
      provider: npm
      email: addons-dev-automation+npm@mozilla.com
      # Note that cleanup runs *after* the before_deploy script.
      skip_cleanup: true
      # This is the API key for npm user 'addons-robot'
      api_key:
        secure: CVUpq7hp1/CvAD40vA0cm+5jI7Izlsb83mCNrAt7Qcjb4orFWTHUxE3Y0a5wGS2gAIr5l/hd/CruXdy4EfMVS6GyW5qhTeWxS0b36+t542z4Xlk9eY4UvB5DdKMJKH8RT+Sz8E/Sx6fhISgvQW48rGJCq3ePaH54mLkXLRJW7HqZxSnrAGc8XLiTJOUPKhOzo4AALXvLKDB+doTtHtSDFD+G+kpABMlJBw849V4mGVi/oUpK5Z/tnCjBBKIaU2Cw//2rE0Wo2mN4osq9eUHxNNTA4fTZoEONaDN/zeYhp3IjYc4cRVK611xnhITLW8CJwRSFJYaoPDB0S1sHOuIcl026SC36m01m7vb0RdxzxhTRBcdClSgo0VcqWHjGjZ5knR1s3ztUcOgVbkcuyQ7x03jp7DEe52sH86myzpWpymu6StRXQix4YjkDoGMFczhPmOP+fWYUex87VCsF1f3rdXJSQmtFuM4Tm11E4WoZGaLB5cgKTNZodJ5v6+UK5u3mop59fIJsIrFF+NKCJNnHvegchiLyGiOJb5wYWpnP4/O2XXNvDEtSPJBRGT/fcHVnYBr6hAl6ux/z4ND3xX77hKKnqQk+CrR28aQpURBNJMKFgtW2DcABAXTZ16ezhXsPlIp6/2GXu0VozTTnwPCRhvsl+s+dqqJu0faxSo+vB7s=
      on:
        tags: true

script:
## run eslint, flow and the unit test suite.
- npm run test-coverage

## NOTE: by setting the configured python to /bin/false we are forcing the production mode tests
## to fail if any of the dependencies is a binary dependency that is build using node-gyp.
- npm config set python /bin/false

## run functional test suite in a npm production environment
## (See #1082 for rationale).
- TEST_PRODUCTION_MODE=1 npm run test-functional

## run functional test suite in "npm legacy bundling mode"
## (See #1639 for rationale).
- TEST_PRODUCTION_MODE=1 TEST_LEGACY_BUNDLING=1 npm run test-functional

## NOTE: remove the custom python path from the npm config, and also
## remove production package.json.
- npm config delete python

after_script: npm run publish-coverage


notifications:
  irc:
    channels:
    - irc.mozilla.org#amo-bots
    on_success: change
    on_failure: always
