language: node_js
sudo: false
node_js:
- '0.12'
- '4'
before_install:
- npm install -g npm
script: npm test
notifications:
  irc:
    channels:
    - irc.mozilla.org#amo-bots
    on_success: change
    on_failure: always
